fix: icon not clickable issue
bcgov/nr-site-registry pull request #137
Opened 2024-10-24 22:26 UTC by jaspalsingh-aot

# Description
Fix Side nave bar icon click issue

2024-10-28 14:58 UTC, bolny approved these changes
If there's a way to add a unit test for the click issue (I understand this isn't always possible with frontend work) I think we should have it, otherwise LGTM.

2024-10-28 17:06 UTC, jaspalsingh-aot commented
> If there's a way to add a unit test for the click issue (I understand this isn't always possible with frontend work) I think we should have it, otherwise LGTM.

I have 

> If there's a way to add a unit test for the click issue (I understand this isn't always possible with frontend work) I think we should have it, otherwise LGTM.

 I’ve optimized the code and resolved a bug, but I understand that testing frontend interactions can be a bit more complex. I’d be happy to create a separate ticket to address the test cases, as they may require additional effort. Please let me know  that works.

2024-10-28 22:37 UTC, bolny submitted a review, later dismissed

2024-10-29 16:11 UTC, midhun-aot requested changes
We need to discuss before merging this change.

2024-10-29 17:35 UTC, midhun-aot approved these changes

2024-10-29 17:35 UTC, merged