Feat/srs 542
bcgov/nr-site-registry pull request #76
Opened 2024-10-04 20:11 UTC by jaspalsingh-aot

2024-10-09 23:10 UTC, midhun-aot commented on frontend/site-registry/src/app/features/details/associates/Associate.tsx
> +    if (loggedInUser?.profile.preferred_username?.includes('bceid')) {
Please use the helper method in utility.ts

2024-10-09 23:15 UTC, jaspalsingh-aot commented on frontend/site-registry/src/app/features/details/associates/Associate.tsx
> +    if (loggedInUser?.profile.preferred_username?.includes('bceid')) {
I am waiting for your changes to merge as we discussed regarding use of UserRoleType Enum as we already have UserType Enum

2024-10-09 23:55 UTC, nikhila-aot requested changes

2024-10-09 23:55 UTC, nikhila-aot commented on backend/sites/src/app/dto/sitePartics.dto.ts
> +  partiRoleId: string;
check the spelling, is it partics?

2024-10-09 23:55 UTC, nikhila-aot commented on backend/sites/src/app/dto/sitePartics.dto.ts
> +  partiRoleId: string;
should it be partics?

2024-10-09 23:55 UTC, nikhila-aot commented on backend/sites/src/app/services/site/site.service.ts
> +                `There is no event in database againts event id : ${notation.id}`,
use the logger to log messages

2024-10-09 23:55 UTC, nikhila-aot commented on backend/sites/src/app/services/site/site.service.ts
>  import { LandHistoryService } from '../landHistory/landHistory.service';
recheck this file

2024-10-09 23:55 UTC, nikhila-aot commented on backend/sites/src/app/services/site/site.service.ts
>                  console.log('No changes To Site Associations');
replace console.log with logger

2024-10-10 00:28 UTC, jaspalsingh-aot commented on backend/sites/src/app/services/site/site.service.ts
> +                `There is no event in database againts event id : ${notation.id}`,
done

2024-10-10 00:28 UTC, jaspalsingh-aot commented on backend/sites/src/app/dto/sitePartics.dto.ts
> +  partiRoleId: string;
done

2024-10-10 00:28 UTC, jaspalsingh-aot commented on backend/sites/src/app/dto/sitePartics.dto.ts
> +  partiRoleId: string;
done

2024-10-10 00:29 UTC, jaspalsingh-aot commented on backend/sites/src/app/services/site/site.service.ts
>  import { LandHistoryService } from '../landHistory/landHistory.service';
didn't change anything here

2024-10-10 00:29 UTC, jaspalsingh-aot commented on backend/sites/src/app/services/site/site.service.ts
>                  console.log('No changes To Site Associations');
done

2024-10-10 17:50 UTC, nikhila-aot approved these changes

2024-10-10 17:50 UTC, merged